quarkus.http.port=8080

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:app}
quarkus.datasource.password=${DB_PASSWORD:app}
quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:quarkus_user_auth}
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=false

quarkus.liquibase.migrate-at-start=true
quarkus.liquibase.change-log=db/changelog/db.changelog-master.xml

quarkus.redis.hosts=redis://${REDIS_HOST:localhost}:${REDIS_PORT:6379}
app.redis.enabled=${REDIS_ENABLED:true}

app.jwt.access-token-ttl=PT15M
app.jwt.refresh-token-ttl=P7D
app.jwt.issuer=quarkus-user-auth

smallrye.jwt.sign.key=${JWT_SECRET:change-me}
smallrye.jwt.verify.key=${JWT_SECRET:change-me}
smallrye.jwt.sign.issuer=${app.jwt.issuer}
mp.jwt.verify.issuer=${app.jwt.issuer}

app.cache.user-ttl=PT5M

app.seed.admin.enabled=${ADMIN_SEED_ENABLED:false}
app.seed.admin.username=${ADMIN_USERNAME:admin}
app.seed.admin.email=${ADMIN_EMAIL:admin@example.com}
app.seed.admin.full-name=${ADMIN_FULL_NAME:System Administrator}
app.seed.admin.password=${ADMIN_PASSWORD:Admin123!}

%dev.quarkus.swagger-ui.always-include=true
%dev.quarkus.smallrye-openapi.path=/openapi
%dev.quarkus.swagger-ui.path=/swagger-ui
