CREATE SCHEMA IF NOT EXISTS fastworks_golang;
SET search_path TO fastworks_golang;

ALTER TABLE IF EXISTS roles
    ADD COLUMN IF NOT EXISTS name VARCHAR(50) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS description TEXT,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();

CREATE UNIQUE INDEX IF NOT EXISTS idx_roles_name ON roles (name);
