export const SCHEDULING_SIDEBAR_PERMISSIONS = [
  "SCHEDULE_READ",
  "SCHEDULE_WRITE",
  "SESSION_READ",
  "SESSION_WRITE",
  "SESSION_RESCHEDULE",
] as const;

export const SCHEDULING_GUARD_PERMISSIONS = [
  "SCHEDULE_READ",
  "SCHEDULE_WRITE",
  "SESSION_READ",
  "SESSION_WRITE",
  "SESSION_RESCHEDULE",
] as const;
